version: '3.8'  # Assurez-vous d'utiliser la version appropriée de Docker Compose

services:
  nginx:
    build:
      context: ./nginx  # Le chemin du Dockerfile et des fichiers de construction
      dockerfile: Dockerfile-nginx  # Le nom de votre Dockerfile pour NGINX
    ports:
      - "80:80"  # Mappez le port 80 du conteneur NGINX au port 80 de l'hôte
      - "443:443"  # Mappez le port 443 du conteneur NGINX au port 443 de l'hôte
    depends_on:
      - db  # Si vous avez un service de base de données (dépend de son nom)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Montez le fichier de configuration NGINX
    networks:
      - mynetwork  # Nom du réseau Docker (peut être personnalisé)

networks:
  mynetwork:
    driver: bridge  # Vous pouvez personnaliser les options du réseau si nécessaire
