version: '3.8'

volumes:
  mariadb_data:
  wordpress_data:

networks:
  babreton_network:
    driver: bridge

services:
  nginx:
    build:
      context: ./configs/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/html:/var/www/html
    networks:
      - babreton_network
  mariadb:
    build:
      context: ./configs/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    user: mysql
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - babreton_network
    