version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./configs/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./configs/nginx
      dockerfile: Dockerfile
    image: nginx
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./configs/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/$login/data/mariadb'
      o: 'bind'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      device: '/home/$login/data/wordpress'
      o: 'bind'

networks:
  inception:
    driver: bridge